### ISSUE TITLE
Race condition of test_cases status updates and latency in submission status updates 

### ISSUE THREAD

**Issue by mohitejaikumar** [code100x/algorithmic-arena#32]
![Screenshot 2024-06-12 021826](https://github.com/code100x/algorithmic-arena/assets/124685897/67d81185-18a7-41b3-a717-a5229e0f6e11)

 @hkirat 
Is it correct way of solving this problem since Redis in single threaded so it gives us feature of mutex lock which will help to resolve this .
Since we want three things 
1. Maximum time 
2. Maximum memory 
3. Submission Status (AC or Reject)

These all three things will be handled by submission-callback endpoint 
And Nextjs API used for polling will eventually show data on basis of this Redis 

![Screenshot 2024-06-12 021656](https://github.com/code100x/algorithmic-arena/assets/124685897/91f1baf4-b29b-435e-ba37-8555846abe28)

**Comment by SujithThirumalaisamy** [comment]
Resolved on #40
