### ISSUE TITLE
Merge judge0 and our own db

### ISSUE THREAD

**Issue by hkirat** [code100x/algorithmic-arena#5]
Make our db schema such that judge0 can directly talk to it

**Comment by hkirat** [comment]
This will also get rid of a race condition thats being caused right now where the entry for a test case doesnt reach a database but we receive a callback from judge0
<img width="994" alt="Screenshot 2024-06-07 at 4 56 13 PM" src="https://github.com/code100x/algorithmic-arena/assets/8079861/002341ce-b663-4251-b417-d7258693501e">

**Comment by nimit9** [comment]
Will take this or #6

**Comment by Ankur1493** [comment]
Working on it
