### ISSUE TITLE
(Need help)Problem's are not visible in local development 

### ISSUE THREAD

**Issue by itzamanjain** [code100x/algorithmic-arena#98]
OS: Windows 11 
@nimit9 

![Screenshot 2024-09-18 231413](https://github.com/user-attachments/assets/9975f402-7428-4b37-ad9b-7b609daa20d1)

i changed mount path to this 

```
MOUNT_PATH="D:\\os projects\\algorithmic-arena\\apps\\problems"
```

and in docker file also 
volumes:
      - .\\judge0.conf:/judge0.conf:ro
      - type: bind
        source: "D:\\os projects\\algorithmic-arena\\apps\\problems"

**Comment by sahilc-xd** [comment]
I am also facing the same issue

**Comment by sahilc-xd** [comment]
@hkirat 
Bhaiya plz check

**Comment by sahilc-xd** [comment]
@itzamanjain bro run db seed , it will work in root , run command-->
 pnpm prisma:docker

**Comment by itzamanjain** [comment]
thanks @sahilc-xd . it is working fine :)

**Comment by sahilc-xd** [comment]
@itzamanjain were you able to submit solutions of codes ?
